### ISSUE TITLE
Compliance with the EU GDPR: ask for user's consent to store his / her personal data

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#69]
### Short Description of the issue

Currently, when a new user logs in K-Box for the first time, he / she is asked to agree with the service policy. He / she however is not asked if he consents that his / her personal data (what personal data?) will be stored in the K-Box  and for which aim.

Probably necessary to add an explicit message on this, in order to comply with the EU GDPR?

https://www.eugdpr.org/key-changes.html

> Consent
> The conditions for consent have been strengthened, and companies will no longer be able to use long illegible terms and conditions full of legalese, as **the request for consent must be given in an intelligible and easily accessible form, with the purpose for data processing attached to that consent. Consent must be clear and distinguishable from other matters and provided in an intelligible and easily accessible form, using clear and plain language. It must be as easy to withdraw consent as it is to give it**.​

Concretely, this requires, I guess, the following features:
(1) [at first login] Screen (hiding the rest of the interface) clearly explaining what personal data will be stored, for what aim
[ if the user clicks "Yes, I consent"]: the main K-Box window is displayed
[ if the user clicks "No, I do not consent"]: a warning text informs that he / she will not be able to use the K-box at all, and that all his / her information (Name, Email address) will be deleted

(2) On the user page: possibility to withdraw the consent at any time, with a clear explanation of the consequences (you will loose access to the K-Box, all documents uploaded or modified by you will remain but your name / email will no longer be associated with them, your name and email will be definitely removed from the database)

(3) Possibility to force the feature (1) at next login (for all already running K-Boxes for which the consent has not been previously asked)

### Expected behavior

Explained above

### Steps to reproduce the incorrect behavior

N/A

### General information

N/A

### Screenshots

N/A

**Comment by avvertix** [comment]
The issue is being worked on. We decided to divide it in sub-sequent steps

* [x] Make sure that K-Link and K-Search can live without personal data (#166)
* [x] Make sure that K-Box do not leak personal data (#165 and #167)
* [ ] Explicit request to agree to the configured privacy policy (#176)
